plugins:
  command-list:
    help: 'PLUGINS - use !usage <plugin> for more information'
    usage: "!plugins - List installed plugins\n!usage <plugin> - get usage for a given plugin"
  java-pils:
    usage: '!pils? - Check for javaPils today'
    announce: 'NAME javaPils i dag - PLACE'
    reply: 'Ja! NAME javaPils i dag - PLACE'
    no-reply: 'Ikke i dag :( Hvis ikke noen har lyst ?'
    tweet: 'NAME javaPils i dag - %d. %b - PLACE'
  url-logger:
    usage: 'See http://dukelinks.herokuapp.com for links posted in channel'
  twitter:
    usage: "!tweet message - only for authorized users\n!accounts - list configured accounts"
    tweet-non-owner: 'Sorry NICK, but you are not authorized to tweet'
    tweet-owner: 'OK NICK'
    tweeters: ''
  about:
    usage: '!about - About the bot'
    about: 'A cinch/ruby based IRC bot. See https://github.com/chrissearle/jb_duke'
  friday:
    usage: '!isitfriday? - Is it friday?'
    friday: "Ja! It's Friday, Friday, Gotta get down on Friday"
    not-friday: 'Nei.'
    dow: 5
bot:
  hostname: 'irc.underworld.no'
  channel: '#java.no'
  nick: 'jb_duke'
  real-name: 'javaBin Duke Bot'
  user-name: 'jb_duke'
mongo:
  uri: 'mongodb://localhost'
  db: 'dukebot'
beer:
  locations:
    oslo:
      day-of-week: 2
      announce-hour: 10
      announce-min: 0
      week: 'odd'
      display-name: 'Oslo'
      place: 'Billabong'
tweeter:
  - name: 'javaPils'
    tokens:
      consumer:
        token: '---'
        secret: '---'
      access:
        token: '---'
        secret: '---'
    message:
      mention: 'javaPils: USERNAME (@SCREENNAME) TEXT - https://twitter.com/SCREENNAME/status/ID'
  - name: 'javaBin'
    tokens:
      consumer:
        token: '---'
        secret: '---'
      access:
        token: '---'
        secret: '---'
    message:
      mention: 'javaBin: USERNAME (@SCREENNAME) TEXT - https://twitter.com/SCREENNAME/status/ID'
  - name: 'javazone'
    tokens:
      consumer:
        token: '---'
        secret: '---'
      access:
        token: '---'
        secret: '---'
    message:
      mention: 'javazone: USERNAME (@SCREENNAME) TEXT - https://twitter.com/SCREENNAME/status/ID'
test:
  plugins:
    java-pils:
      tweet: 'Testing javapils announce NAME - %d. %b - week %V - PLACE'
  mongo:
    uri: 'mongodb://localhost'
  bot:
    channel: '#just-testing'
    nick: 'test_duke'
    real-name: 'javaBin Duke Test'
    user-name: 'test_duke'
