plugins:
  command-list:
    usage: "!c - List commands"
  java-pils:
    usage: "!pils? - Check for javaPils today"
  url-logger:
    usage: "See http://dukelinks.herokuapp.com for links posted in channel"
  twitter:
    conf: ""
bot:
  hostname: "irc.underworld.no"
  channel: "#java.no"
  nick: "jb_duke"
  real-name: "javaBin Duke Bot"
  user-name: "jb_duke"
mongo:
  uri: mongodb://localhost
  db: dukebot
beer:
  locations:
    oslo:
      day-of-week: 2
      announce-hour: 10
      announce-min: 0
      week: 'odd'
      display-name: 'Oslo'
      place: 'Billabong'
tweeter:
  consumer:
    token: ---
    secret: ---
  access:
    token: ---
    secret: ---
  message:
    beer: "LOC javaPils i dag - %d. %b - PLACE"
    mention: "Nevnt: USERNAME (@SCREENNAME) TEXT - https://twitter.com/SCREENNAME/status/ID"
test:
  mongo:
    uri: mongodb://localhost
  bot:
    channel: "#just-testing"
    nick: "test_duke"
    real-name: "javaBin Duke Test"
    user-name: "test_duke"
  tweeter:
    message:
      beer: "Testing javapils announce LOC - %d. %b - week %V - PLACE"
