plugins:
  command-list:
    usage: '!c - List commands'
  java-pils:
    usage: '!pils? - Check for javaPils today'
    announce: 'NAME javaPils i dag - PLACE'
    reply: 'Ja! NAME javaPils i dag - PLACE'
    no-reply: 'Ikke i dag :( Hvis ikke noen har lyst ?'
    tweet: 'NAME javaPils i dag - %d. %b - PLACE'
  url-logger:
    usage: 'See http://dukelinks.herokuapp.com for links posted in channel'
  twitter:
    usage: '!tweet message - only for authorized users'
    tweet-non-owner: 'Sorry NICK, but you are not authorized to tweet'
    tweet-owner: 'OK NICK'
    tweeters: ''
  about:
    usage: '!about - About the bot'
    about: 'A cinch/ruby based IRC bot. See https://github.com/chrissearle/jb_duke'
bot:
  hostname: 'irc.underworld.no'
  channel: '#java.no'
  nick: 'jb_duke'
  real-name: 'javaBin Duke Bot'
  user-name: 'jb_duke'
mongo:
  uri: 'mongodb://localhost'
  db: 'dukebot'
beer:
  locations:
    oslo:
      day-of-week: 2
      announce-hour: 10
      announce-min: 0
      week: 'odd'
      display-name: 'Oslo'
      place: 'Billabong'
tweeter:
  consumer:
    token: '---'
    secret: '---'
  access:
    token: '---'
    secret: '---'
  message:
    mention: 'Nevnt: USERNAME (@SCREENNAME) TEXT - https://twitter.com/SCREENNAME/status/ID'
test:
  plugins:
    java-pils:
      tweet: 'Testing javapils announce NAME - %d. %b - week %V - PLACE'
  mongo:
    uri: 'mongodb://localhost'
  bot:
    channel: '#just-testing'
    nick: 'test_duke'
    real-name: 'javaBin Duke Test'
    user-name: 'test_duke'
